image: atlassian/default-image:3
options:
  docker: true
definitions:
  services:
    docker:
      memory: 2048
  steps:
    - step: &build-push-to-ecr
        name: Build Docker image
        script:
          - apt update && apt install awscli -y 
          - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          - aws configure set region $AWS_DEFAULT_REGION
          - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 387232581030.dkr.ecr.us-east-1.amazonaws.com
          - COMMIT_HASH=$(git rev-parse --short=7 $BITBUCKET_COMMIT) 
          - docker build -t test  .
          - docker tag test:latest $REPOSITORY_URL:$COMMIT_HASH
          - docker push $REPOSITORY_URL:$COMMIT_HASH 
          
        #artifacts:
         # - tmp-image.docker
    - step: &update-to-manifest
        name: update to manifest 
        script:
          - echo "cloning the manifest repo"
          #- git clone git@bitbucket.org:catchpenguins/argocd.git
          - git clone $TARGET_REPO_URL 
          - ls -la 
          - cd argocd 
          #- git checkout test
          - echo "update manifest"
          - COMMIT_HASH=$(git rev-parse --short=7 $BITBUCKET_COMMIT)
          - sed -i '18s/.*/        image:\ CONTAINER_IMAGE/' manifest/deployment.yml
          - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URL:$COMMIT_HASH"'@' manifest/deployment.yml
          - git config --global user.email "niyaz@easydeploy.cloud"
          - git config --global user.name "niyaz1996"
          - git add .
          - git commit -m "latest build image $COMMIT_HASH" || echo "it is already up to date"
          - git push 

pipelines:
    branches:
      master:
        - step: *build-push-to-ecr
        - step: *update-to-manifest 
        
 
   